### ISSUE TITLE
clob: Reduce zkvm input state / investigate state layout

### ISSUE THREAD

**Issue by emostov** [InfinityVM/InfinityVM#197]
Right now the canonical clob state is

https://github.com/InfinityVM/InfinityVM/blob/8b98d36bbd332525650bf8455490110864cf71b2/clob/core/src/lib.rs#L34-L40

At the very least, I think this can be improved by pulling out the order status map since that does not need to be guaranteed by the coprocessor

My question is, do we still need to maintain order status somewhere? I could see us keeping a table for fills and then constructing order status on the fly, but we would need to introduce a DB with a table like api or create a table like abstraction over our existing KVDB api. 

Feel free to add any discussion here

**Comment by lucasege** [comment]
Closing CLOB issues as stale in favor of ongoing work on GTX
