### ISSUE TITLE
clob: Add signature verification for each order

### ISSUE THREAD

**Issue by MaanavKhaitan** [InfinityVM/InfinityVM#204]
We want to add signature verification for each order submitted by users, in the zkVM program. This is to prevent the CLOB server from just including fake orders in the batch and stealing user funds. More context here: https://ethos-stake.slack.com/archives/C069EV8ELQ2/p1725770296851419

**Comment by lucasege** [comment]
Closing as stale for now, all ongoing CLOB related work will be within GTX
