### ISSUE TITLE
clob: Use state root and merkle proofs instead of passing in entire state

### ISSUE THREAD

**Issue by MaanavKhaitan** [InfinityVM/InfinityVM#320]
Currently, the CLOB server submits the entire state to the coprocessor.

[We decided to remove the `state` field](https://hackmd.io/-ZIeNQD5R16I9qf4J35Dpg?view) and so now the CLOB needs to send state root + merkle proofs for the relevant state values.

Also need to uncomment and update the CLOB tests to work with this.

**Comment by lucasege** [comment]
Closing as stale for now, all ongoing CLOB related work will be within GTX
