### ISSUE TITLE
coprocessor-node: build queue abstraction over DB

### ISSUE THREAD

**Issue by emostov** [InfinityVM/InfinityVM#340]
We need persistent queues for a few use cases in the coprocessor. The main one is job relay ordering per consumer (user). 

We want to guarantee that we relay consumer jobs in an order the specify. So for each consumer we need to be able to keep a queue. The queue needs to be persistent. This queue should likely be implemented as a linked list where each node is a reth db entry. 

Ideally it can expose a api like

```rust
let queue = Queue::load(&db, queue_key)?;

// add items to front
queue.push_front(item1)?;

// see what item is on the back
let item = queue.peek_back();

// remove the item on the back
let _ = queue.pop_back();
```

Am I guessing it will need two tables - one for queue metadata and one for the nodes.

```struct
// In table 1
Queue {
   // keys are for table 2
   head: Key,
   tail: Key
}

// In table 2
Node<V: Serialize> {
    prev: Option<Key>
    value: V,
    next: Option<Key>
}
```

It should be fine to use a 32 byte queue key. For the first use case we will probably just use the consumer address as the key.

For flexibility. the queue should be generic over the stored value. We will also want to use this abstraction for a generalized dead letter queue.
our reth db crate: https://github.com/InfinityVM/InfinityVM/tree/main/crates/db/src

**Comment by MaanavKhaitan** [comment]
can we close this? now that https://github.com/InfinityVM/InfinityVM/pull/355 is merged
