### ISSUE TITLE
sp1 builder

### ISSUE THREAD

**Issue by twoshark** [InfinityVM/InfinityVM#347]
# What

Create a sp1 builder image for use by our sp1 based rust programs.

1. Create a Dockerfile whose final image allows for an sp1 rust program to be built. Something like [this](https://github.com/InfinityVM/infra/blob/main/docker/risc0-builder/Dockerfile)
2. Locally build the sp1 image & tag it
```
docker build -f Dockerfile.sp1 -t  sp1:latest
```
3. Create a second Dockerfile that imports `sp1:latest` and builds an sp1 rust program
4. Build the second Dockerfile.
```
docker build -f Dockerfile.sp1test 
```
5. If it builds, re-tag your sp1 image
```
docker tag sp1:latest us-docker.pkg.dev/infinityvm-core-artifacts/docker/sp1builder:vX.X.X
```
6. Push the image to GAR:
```
docker push us-docker.pkg.dev/infinityvm-core-artifacts/docker/sp1builder:vX.X.X
```
7. Evaluate the build time, if it's <30 min to build locally, you can try to create a GHA for it and see if will build there.

**Comment by emostov** [comment]
No longer needed since we don't build zkvm programs in any docker files right now
