### ISSUE TITLE
add delete method to kairos-trie

### ISSUE THREAD

**Issue by emostov** [InfinityVM/InfinityVM#348]
Currently, the [kairos-trie](https://github.com/cspr-rad/kairos-trie) does not implement a remove method. The kairos trie is a merkle tree specifically optimized for zkvm applications. Importantly, it allows us to easy create snapshots of data read/writes that we can then pass along to the zkvm for easy verification. You can learn more about the project in this [blog post](https://medium.com/casperblockchain/introducing-kairos-trie-an-efficient-merkle-trie-for-zk-vms-43e023786e64)

 It only has [get](https://github.com/cspr-rad/kairos-trie/blob/e649cb702d12f4711714fc37d44a2186b20007f0/src/transaction.rs#L250) and [insert](https://github.com/cspr-rad/kairos-trie/blob/e649cb702d12f4711714fc37d44a2186b20007f0/src/transaction.rs#L321). 

To close this issue, we should add a delete method to the kairos-trie `Transaction` type. Ideally, we can merge this in the upstream repo so we don't have to maintain a fork.

**Comment by Avi-D-coder** [comment]
Done https://github.com/InfinityVM/zkvm-merkle-trees/commit/83af99aeb96f6e7749e9b6378ea1ae713f27dff8
